### ISSUE TITLE
Make Annovar multithreaded

### ISSUE THREAD

**Issue by rkositsky** [labdave/CloudConductor#222]
Annovar seems to have a multithreading option that is not being used by Cloud Conductor.
Adding "-thread {nr_cpus}" to the Annovar command would parallelize this step.

See the update from 2015Dec14 on [http://annovar.openbioinformatics.org/en/latest/misc/whatsnew/](http://annovar.openbioinformatics.org/en/latest/misc/whatsnew/).

**Comment by ripanea** [comment]
Fixed by commit bc8a1b5ca
